version: 2.1
executors:
  docker-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project
jobs:
  build_and_push:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$CIRCLE_SHA1 .
      - run:
          name: Login to ECR
          command: |
            aws ecr get-login-password --region $AWS_REGION | \
            docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - run:
          name: Push Docker Image
          command: docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$CIRCLE_SHA1
workflows:
  build_and_deploy:
    jobs:
      - build_and_push:
          context: aws-ecr-context
