version: 2.1
executors:
  node-executor:
    docker:
      - image: cimg/node:18.20.5
    working_directory: ~/project
jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Run tests
          command: echo 'replace me with real tests!' && false
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Build an artifact
          command: touch example.txt
      - store_artifacts:
          path: example.txt
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: "#e.g. ./deploy.sh"
      - run:
          name: found empty repo
          command: ":"
  evals-test-assertions-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - evals/test:
          assertions: assertions.json
          metrics: eval_results.json
          results: test_results.xml
  playwright-e2e-tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Playwright Tests
          command: npx playwright test
workflows:
  example:
    jobs:
      - test:
          context:
            - LlamaAPI-milanhe92@gmail.com
            - OpenAI-milanhe92@gmail.com
            - Anthropic-milanhe92@gmail.com
            - AmazonBedrock-milanhe92@gmail.com
            - Gemini-milanhe92@gmail.com
            - CloudflareVectorize-milanhe92@gmail.com
            - AmazonS3-milanhe92@gmail.com
            - ChromaDB-milanhe92@gmail.com
            - Supabase-milanhe92@gmail.com
      - build:
          requires:
            - test
          context:
            - LlamaAPI-milanhe92@gmail.com
            - OpenAI-milanhe92@gmail.com
            - Anthropic-milanhe92@gmail.com
            - AmazonBedrock-milanhe92@gmail.com
            - Gemini-milanhe92@gmail.com
            - CloudflareVectorize-milanhe92@gmail.com
            - AmazonS3-milanhe92@gmail.com
            - ChromaDB-milanhe92@gmail.com
            - Supabase-milanhe92@gmail.com
      - deploy:
          requires:
            - test
          context:
            - LlamaAPI-milanhe92@gmail.com
            - OpenAI-milanhe92@gmail.com
            - Anthropic-milanhe92@gmail.com
            - AmazonBedrock-milanhe92@gmail.com
            - Gemini-milanhe92@gmail.com
            - CloudflareVectorize-milanhe92@gmail.com
            - AmazonS3-milanhe92@gmail.com
            - ChromaDB-milanhe92@gmail.com
            - Supabase-milanhe92@gmail.com
  test-eval-workflow:
    jobs:
      - evals-test-assertions-job
  playwright-workflow:
    jobs:
      - playwright-e2e-tests
