version: 2.1
executors:
  ios-executor:
    macos:
      xcode: 14.0.0
    working_directory: ~/project
jobs:
  build_ios:
    executor: ios-executor
    steps:
      - checkout
      - run:
          name: Install Fastlane
          command: bundle install
      - run:
          name: Run Fastlane
          command: bundle exec fastlane ios build
workflows:
  version: 2
  build:
    jobs:
      - build_ios
